-- ============================================================
-- Migration: Shipping integration with LogManager
-- Date: 2026-06-03
-- Description: Adds shipping tracking columns to orders. The `logmanager_envio_id`
--              is the idEnvio we send to LogManager (generated by us, kept stable
--              for retries). `shipping_status` tracks the carrier's status
--              independently from `status` (the order's logical state) so we can
--              audit the carrier flow without losing the order's own lifecycle.
-- ============================================================

ALTER TABLE orders
  ADD COLUMN IF NOT EXISTS logmanager_envio_id text,
  ADD COLUMN IF NOT EXISTS shipping_status text,
  ADD COLUMN IF NOT EXISTS shipping_dispatched_at timestamptz,
  ADD COLUMN IF NOT EXISTS shipping_last_error text;

CREATE INDEX IF NOT EXISTS orders_logmanager_envio_id_idx
  ON orders(logmanager_envio_id)
  WHERE logmanager_envio_id IS NOT NULL;
